services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - "DB_PATH=:memory:"
